#!/bin/bash

echo 'xterm -title "A" -hold -e "./final topology.txt A | tee routing-outputA.txt" & sleep 1
xterm -title "B" -hold -e "./final topology.txt B | tee routing-outputB.txt" & sleep 1
xterm -title "C" -hold -e "./final topology.txt C | tee routing-outputC.txt" & sleep 1
xterm -title "D" -hold -e "./final topology.txt D | tee routing-outputD.txt" & sleep 1
xterm -title "E" -hold -e "./final topology.txt E | tee routing-outputE.txt" & sleep 1
xterm -title "F" -hold -e "./final topology.txt F | tee routing-outputF.txt" & sleep 1' | shuf > exec
chmod 777 exec
./exec
rm exec
